#!/usr/bin/env bash
# stopped our 4-to_infinity_and_beyond process
# using ctrl+c in the previous task
#a Bash script that stops 4-to_infinity_and_beyond process

kill "$(pgrep -f 4-to_infinity_and_beyond)"
